backend:
  name: git-gateway
  branch: main
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    file: content/blog.json
    fields:
      
        widget: list
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: datetime }
          - { name: title, label: Title }
          - { name: preview, label: Preview, widget: markdown }
          - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: blog
    format: json
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: preview, label: Preview, widget: markdown }
      - { name: body, label: Body, widget: markdown }
  - name: settings
    label: Settings
    files:
      - name: settings
        label: Settings
        file: content/general_settings.json
        fields:
        - { name: title, label: Title}
        - { name: logo, label: Logo, widget: image }
        - { name: logoInverted, label: Logo Inverted, widget: image }
        - { name: insta_link, label: Instagram Link, widget: string }
        - { name: fb_link, label: Facebook Link, widget: string }
        - { name: linkedin_link, label: LinkedIn Link, widget: string }
        - { name: contact_mail, label: Contact Mail, widget: string }
  - name: about
    label: About
    files:
      - name: about
        label: About
        file: content/de_about.json
        fields:
        - { name: title, label: Title}
        - { name: visual, label: Visual, widget: image }
        - { name: aboutText, label: About Text, widget: markdown }
  - name: Experiences
    label: Experiences
    files:
      - name: Experiences
        label: Experiences
        file: content/de_experiences.json
        fields:
          - label: Experience
            name: experience
            widget: list
            fields:
            - { name: title, label: Title }
            - { name: visual, label: Visual, widget: image }
            - { name: alt_text, label: Alternative Text, widget: string }
            - { name: link, label: Link, widget: string }
            - { name: flex, label: Proportion, widget: number, value_type: int, min: 1, max: 10  }
        