backend:
  name: git-gateway
  branch: main
media_folder: static/assets
public_folder: /assets
collections:
  - name: settings
    label: Settings
    files:
      name: settings
      label: Settings
      file: content/general_settings.json
      fields:
        - { name: title, label: Title}
        - { name: insta_link, label: Instagram Link, widget: string }
        - { name: fb_link, label: Facebook Link, widget: string }
        - { name: linkedin_link, label: LinkedIn Link, widget: string }
        - { name: contact_mail, label: Contact Mail, widget: string }
  
        