backend:
  name: git-gateway
  branch: main
media_folder: static/assets
public_folder: /assets
collections:

  - name: seo
    label: SEO
    files: 
      - name: general
        label: General
        file: content/seo.json
        fields:
        - { name: title, label: Title, widget: text }
        - { name: description, label: Description, widget: text }
        - { name: keywords, label: Keywords, widget: text }
  - name: settings
    label: Settings
    files: 
      - name: general
        label: General
        file: content/settings.json
        fields:
        - { name: title, label: Title, widget: hidden }
        - { name: email, label: Email, widget: text }
